# Local development secrets for the Streamlit app.
# The password hash corresponds to the plaintext value "admin".
editor_password_hash = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"

[github]
# Provide real values when integrating with GitHub.
token = ""
repo = ""
path = "form_schema.json"
branch = "main"
api_url = "https://api.github.com"
